# Generated by Django 2.1 on 2020-03-13 16:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbnormalSignData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timeData', models.DateTimeField(auto_now_add=True)),
                ('machineName', models.CharField(default='', max_length=100)),
                ('alarm', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='AlarmData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timeData', models.DateTimeField(auto_now_add=True)),
                ('machineName', models.CharField(default='', max_length=100)),
                ('alarm', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='DCData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timeData', models.DateTimeField(auto_now_add=True)),
                ('machineName', models.CharField(default='', max_length=100)),
                ('dcV', models.FloatField(default=0.0)),
                ('dcA', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='EmailData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('machineName', models.CharField(default='', max_length=100)),
                ('replacePartEmail', models.EmailField(default='', max_length=100)),
                ('sludgeOutEmail', models.EmailField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InfoData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timeData', models.DateTimeField(auto_now_add=True)),
                ('machineName', models.CharField(default='', max_length=100)),
                ('drumFrq', models.FloatField(default=0.0)),
                ('pressrollFrq', models.FloatField(default=0.0)),
                ('sludgesupplyFrq', models.FloatField(default=0.0)),
                ('sludgespreadFrq', models.FloatField(default=0.0)),
                ('drumcolingWater', models.FloatField(default=0.0)),
                ('transformersTemp', models.FloatField(default=0.0)),
                ('sludgeInput', models.FloatField(default=0.0)),
                ('sludgeOutput', models.FloatField(default=0.0)),
                ('inputwaterRate', models.FloatField(default=0.0)),
                ('outputwaterRate', models.FloatField(default=0.0)),
                ('leftBalance', models.IntegerField(default=0)),
                ('rightBalance', models.IntegerField(default=0)),
                ('kW', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='OperatingData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('colIndex', models.IntegerField(default=0)),
                ('startingTime', models.CharField(default=django.utils.timezone.now, max_length=500)),
                ('machineName', models.CharField(default='', max_length=100)),
                ('opName', models.CharField(default='', max_length=100)),
                ('totalOpTime', models.IntegerField(default=0)),
                ('referenceTime', models.IntegerField(default=0)),
                ('alarmTime', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OperatingTimeData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timeData', models.DateTimeField(auto_now_add=True)),
                ('machineName', models.CharField(default='', max_length=100)),
                ('totalOpTime', models.IntegerField(default=0)),
                ('drumCoating', models.IntegerField(default=0)),
                ('sludgeScraper', models.IntegerField(default=0)),
                ('filterCleaner', models.IntegerField(default=0)),
                ('closeSensor', models.IntegerField(default=0)),
                ('waterTankSensor', models.IntegerField(default=0)),
                ('filter', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SludgeInOutData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timeData', models.DateTimeField(auto_now_add=True)),
                ('receiveTime', models.FloatField(default=0.0)),
                ('machineName', models.CharField(default='', max_length=100)),
                ('sludgeInput', models.FloatField(default=0.0)),
                ('sludgeOutput', models.FloatField(default=0.0)),
            ],
        ),
    ]
